### ISSUE TITLE
Is the example broken?

### ISSUE THREAD

**Issue by cfcs** [oklm-wsh/Callipyge#2]
No matter what I do I end up with:
```
utop # r;;
- : int array =  [|0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0;
                   0; 0; 0; 0; 0; 0|]
```

**Comment by cfcs** [comment]
ping @dinosaure :)

**Comment by dinosaure** [comment]
In fact, I look the problem now.

**Comment by dinosaure** [comment]
Sorry for delay, I just look rapidly what is going on and I think, I need to reimplement Callipyge (so, I will take a time to do that). So, if you have a specific task, it's the good moment to improve the API 😃 !

I think, I will delete the functor first and keep the current API.

**Comment by cfcs** [comment]
I don't think I have need for much beyond:
```
type _ key
val secret_key_of_string : string -> secret key
val public_key_of_string : string -> public key
val string_of_key : _ key -> string

val ecdh : public key -> secret key -> string
val public_of_secret : secret key -> public key
```

Perhaps a bit more high-level API would be nice (with a dependency on digestif to do the `sha512` / `sha512/256` / `whatever is used` hashing from secret key seed -> secret key) to be compatible with the RFCs.

**Comment by TealG** [comment]
would be great to have this working -- I'm looking forward to a Noise protocol implementation and would be useful for SSH & TLS, too.

**Comment by dinosaure** [comment]
@TealG yeah sorry for the delay, I'm focused on mirage/digestif and mirage/ocaml-git. But I did the release of `digestif` yesterday, so I have a free time to focus on Callipyge 😄 !

**Comment by emillon** [comment]
I believe that this can now be closed.
